name: CI Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  analyze:
    name: CodeQL-security
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python
      - uses: github/codeql-action/analyze@v3

  trivy-scan:
    name: Dependency security scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'requirements.txt'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

  build-scan-push-deploy:
    name: Build, scan, push, deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t guestbook:latest .

      - name: Scan image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'guestbook:latest'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push image
        run: |
          IMAGE_URI="${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest"
          docker tag guestbook:latest "$IMAGE_URI"
          docker push "$IMAGE_URI"

      - name: Fetch current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ secrets.ECS_TASK_DEFINITION }} \
            --query taskDefinition > taskdef.json

      - name: Render new task definition
        id: render
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: taskdef.json
          container-name: ${{ secrets.CONTAINER_NAME }}
          image: ${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Sync frontend to S3
        run: |
              aws s3 cp templates/index.html \
              s3://${{ secrets.S3_BUCKET }}/index.html

      - name: Invalidate the cloudfront cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}} \
          --paths "/*"
  
  health-check:
    name: post-deply health check
    needs: build-scan-push-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.11'
      - name: Install requests
        run: pip install requests

      - name: run the health check
        env: APP_URL=${{secrets.APP_URI}}
        run: python scripts/health_check.py
    
