name: CI Workflow

on:
  push:
    branches:
    - main

jobs:
  analyze:
    name: CodeQl-seucurity
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: Initialize CodeQl
        uses: github/codeql-action/init@v3
        with: 
          languages: python

      - name: perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
  
  trivy-scan:
    name: Dependency security scan
    runs-on: ubuntu-lastes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Scan the requirements.txt file
        uses: aquasecurity/trivy-action@master
        with:
           scan-type: 'fs'
           scan-ref: 'requirements.txt'
           formate: 'table'
           exite-code: '1'
           severity: ' CRITICAL_HIGH'